### ISSUE TITLE
Surface Pro 5 wakes up on lid closing (but not opening)

### ISSUE THREAD

**Issue by ceever** [linux-surface/surface-gpe#2]
**Issue**
Whenever I turn my Surface into suspend mode, it will wake up on lid (aka Typecover) closing, but not on lid opening.

This way unfortunately I can never put my Surface into Suspend and then close the lid. Therefore currently, I am running Suspend with a 5 seconds delay, so the lid can be closed before Suspend is executed. When the lid is closed before Suspend is initiated, the Surface remains in Suspend afterwards.

However, the Suspend mode is not interrupted on lid opening either, even though the Typecover (aka lid) starts illuminating the keys after a few seconds delay. No key will wake the device, only the Power Button will do this.

 My current workaround is to deactivate the Surface GPE: "sudo modprobe -r surface_gpe" ... after which I can close and open the lid without affecting the Suspend mode of device.

**Expected behaviour**
Surface does not wakeup at all on closing the lid/Typecover.

**System information**
Machine: Surface Pro 5 (2017)
Kernel: 5.19.13-surface
OS: Ubuntu / LXQt / 20.04

**Comment by qzed** [comment]
The `surface-gpe` module doesn't do anything other than marking the interrupts as wakeup capable and we can't differentiate between closing and opening just by this (this needs to be done in the lid driver itself). It's possible that we may need to modify `surface-gpe` to essentially hook the GPE up to the lid device (so that the lid knows that the GPE is the wakeup source), but I'm not sure about that yet. So let's handle this at https://github.com/linux-surface/linux-surface/issues/1060 for now.
